package com.nt.controller;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;

import com.wc.core.AbstractDataAccessObject;

/**
 * 
 * @author nit
 */
public class LineChart extends javax.swing.JFrame {

	/**
	 * Creates new form PieChart
	 */
	public LineChart() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new javax.swing.BoxLayout(getContentPane(),
						javax.swing.BoxLayout.LINE_AXIS));

		jButton1.setText("Start Report");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Calibri", 1, 18))); // NOI18N

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 393,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				0,
																				530,
																				Short.MAX_VALUE))
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton1)
										.addContainerGap()));

		getContentPane().add(jPanel1);

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		/*
		 * DefaultCategoryDataset dcd = new DefaultCategoryDataset();
		 * dcd.setValue(68.83, "Marks", "Ganesh"); dcd.setValue(43.89, "Marks",
		 * "Siva"); dcd.setValue(87.16, "Marks", "Rajesh"); dcd.setValue(35.12,
		 * "Marks", "Hari"); dcd.setValue(45.12, "Marks", "Mahesh");
		 * dcd.setValue(88.09, "Marks", "Rupa"); dcd.setValue(81.23, "Marks",
		 * "Jogendra"); JFreeChart chart =
		 * ChartFactory.createLineChart3D("Student Record", "Student Name",
		 * "Student Marks", dcd, PlotOrientation.VERTICAL, true, true, false);
		 * CategoryPlot plot = chart.getCategoryPlot();
		 * 
		 * plot.setBackgroundPaint(Color.BLACK); ChartFrame charFrame = new
		 * ChartFrame("Student Record", chart, true);
		 * charFrame.setVisible(true);
		 * 
		 * charFrame.setSize(500, 500);
		 */
		try {

			String query = "SELECT  ename,age FROM EMPLOYEEREG";
			JDBCCategoryDataset jdbcdataset = new JDBCCategoryDataset(
					AbstractDataAccessObject.getConnection(), query);
			JFreeChart chart = ChartFactory.createLineChart(
					"Employee Report", "Employee Name", "Employee age",
					jdbcdataset, PlotOrientation.VERTICAL, false, true, false);
			BarRenderer bar = new BarRenderer();
			CategoryPlot plot=new CategoryPlot();
			ChartFrame frame=new ChartFrame("Employee Report",chart);
			frame.setVisible(true);
			frame.setSize(400,650);
			
			
			
			
			//transcation
			String tquery = "SELECT  ENAME,AMOUNT FROM TRANSACTION";
			JDBCCategoryDataset tjdbcdataset = new JDBCCategoryDataset(
					AbstractDataAccessObject.getConnection(), tquery);
			JFreeChart tchart = ChartFactory.createLineChart(
					"Employee Transaction Report", "Employee Name", "Employee AMOUNT",
					tjdbcdataset, PlotOrientation.VERTICAL, false, true, false);
			ChartFrame tframe=new ChartFrame("Employee Transaction Report",tchart);
			tframe.setVisible(true);
			tframe.setSize(400,650);
			
			
			//medical Details
			
			
			String querymedical = "SELECT  ename,AGE FROM MEDICAL";
			JDBCCategoryDataset jdbcdatasetmedical = new JDBCCategoryDataset(
					AbstractDataAccessObject.getConnection(), querymedical);
			JFreeChart chartmedical = ChartFactory.createLineChart(
					"Employee Medical  Report", "Employee Name", "Employee Medical Age",
					jdbcdatasetmedical, PlotOrientation.VERTICAL, false, true, false);

			ChartFrame framemedical=new ChartFrame("Employee Medical Report",chartmedical);
			framemedical.setVisible(true);
			framemedical.setSize(400,650);
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	
	/*
	 * public static void main(String args[]) { Set the Nimbus look and feel
	 * //<editor-fold defaultstate="collapsed"
	 * desc=" Look and feel setting code (optional) "> If Nimbus (introduced in
	 * Java SE 6) is not available, stay with the default look and feel. For
	 * details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
	 * catch (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(LineChart
	 * .class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(LineChart
	 * .class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(LineChart
	 * .class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger
	 * .getLogger(LineChart.class.getName()).log(java.util.logging.Level.SEVERE,
	 * null, ex); } //</editor-fold> //</editor-fold>
	 * 
	 * Create and display the form java.awt.EventQueue.invokeLater(new
	 * Runnable() { public void run() { new LineChart().setVisible(true); } });
	 * }
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration
}
